### ISSUE TITLE
Can you please make a version of this mod for MC 1.7.10?

### ISSUE THREAD

**Issue by HurricaneBoy13** [necauqua/chiseled-me#64] opened 2020-09-12 15:59 UTC
Hi,
I have been using 1.7.10 for so many mods. The only kind of mod I could never get was a player-resizing mod.
Chiseled Me could be a great replacement for Gulliver's Mod if it were for 1.7.10, not just 1.10.2 and 1.12.2.
So can you please update this mod to a 1.7.10 version for MC?
Sincerely,
HurricaneBoy13

**Comment by necauqua** [comment] 2020-09-12 16:53
Well the problem is that I will have a hard-hard time even updating it to 1.15, because this mod applies a *ton* of bytecode patches, each of which completely breaks once you change the version of the game (thats why 1.11 was so bad - had some badly updated patches), and so each of them needs to be revised when a version update occurs.

At the moment the priority is 1.15 or even to finally release the latest 1.12 with a ton of fixes that is only tested in [discord](https://discord.necauqua.dev) atm, sadly.

Anyway I think that version support requests are out of scope for GH issues so I am closing this here, but you can jump into discord if you want more info/discuss/get that beta

**Closed as completed by necauqua** 2020-09-12 16:53 UTC
Labels: invalid
