### ISSUE TITLE
Cannot move while constantly shrinking

### ISSUE THREAD

**Issue by Catlord-3** [necauqua/chiseled-me#68] opened 2020-09-24 03:37 UTC
Basically if i constantly set my size to be slightly smaller, i cannot really move at all, like i am being teleported back to where i was. I tested using latest beta with only chiseled me. I saw a video on someone doing a challenge using this idea, and i have no idea why it does not work in the latest beta. I tested in the latest release and it works fine there. I have no idea why this is and i hope you can fix this.

Video: https://www.youtube.com/watch?v=mmHdjNOt0sQ

Command used (in repeating command block) /sizeof @a multiply 0.999 (this number is for testing purposes, can be changed)

**Comment by Catlord-3** [comment] 2020-09-24 03:48
Also tested using divide instead of multiply, same issue, but setting size really small over a long time actually works. I would still appriciate this being fixed though. Thank you for reading this!

**Comment by necauqua** [comment] 2020-11-24 19:18
Ok I'm finally back to working on this project, closing this a duplicate of #66

**Closed as completed by necauqua** 2020-11-24 19:18 UTC
Labels: bug
