### ISSUE TITLE
unknown crash

### ISSUE THREAD

**Issue by idk-what-to-put-here** [necauqua/chiseled-me#76] opened 2020-12-23 11:59 UTC
when i try to use the mod with a small amount of mods i have it keeps crashing and even removing the LLIbrary mod i use it still has the same crash message which is "The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
Exit Code: -1"
below is a list of the mods i have in the folder
![mods folder](https://user-images.githubusercontent.com/76520419/102994029-5df72b80-4572-11eb-9277-66a536f745d3.jpg)

**Comment by necauqua** [comment] 2020-12-25 10:25
Well you'd need to provide the `debug.log` file for me to say anything, but well, some other mod changes the EntityRenderer class in an incompatible way :shrug: 
You may want to try to identify which mod does that exactly.

**Comment by necauqua** [comment] 2021-01-17 23:24
Given your mod list closing it as duplicate of #62.
If it crashes for you without the llibrary mod you are free to open a new issue.

**Closed as completed by necauqua** 2021-01-17 23:24 UTC
Labels: duplicate, crash

**Comment by Zrules987** [comment] 2022-07-05 12:36
The thing that is crashing your game is Custom Mob spawner
idk why but all that mod does is crash servers and games
Mo creatures can run without custom mob spawners
I hope this helped :)
