### ISSUE TITLE
Crash with Quark+AutoRegLib

### ISSUE THREAD

**Issue by MarkColo2** [necauqua/chiseled-me#47] opened 2020-06-12 19:56 UTC
discovered these while trying to add Chiseled Me to a 1.12.2 Hexxit pack from Twitch.

I trimmed it down to just one mod that causes the crash:

Quark - crashed On Forge 14.23.6.2854  (log attached)
------------------------------
chiseled-me-1.12.2-2.0.0.1.jar
Quark-r1.6-177.jar
AutoRegLib-1.3-32.jar   (required by Quark)

[Chiseled-me, Quark, AutoregLib Crash.log](https://github.com/necauqua/chiseled-me/files/4772941/Chiseled-me.Quark.AutoregLib.Crash.log)

**Comment by MarkColo2** [comment] 2020-06-12 20:01
Was trying to add chiseled-me to a Hexxit 1.12.2 pack that I got from Twitch.  Did some binary searching to narrow the incompatibility down to this mod and its required library.

**Comment by necauqua** [comment] 2020-06-13 05:32
Quark? Oh, maybe makes sense, they must do something with bytecode too.
Will check this too.

**Comment by necauqua** [comment] 2020-06-23 12:51
Closing as duplicate of #32 
Yeah I am going over the issues atm

**Closed as completed by necauqua** 2020-06-23 12:51 UTC
Labels: duplicate, crash, mod compat
