### ISSUE TITLE
Taking constant damage on < 1/32 size with the up, down, and all around mod (broken hitbox)

### ISSUE THREAD

**Issue by SkyfrostgamingYT** [necauqua/chiseled-me#43] opened 2020-05-05 02:37 UTC
When ever i try to scale lower than 1/32, i start taking damage in survival. How do I fix this?

**Expected behavior**
to be able to scale at least to 1/64 without taking damage

**Additional information:**
- Forge version: 1.12.2-2838
- Mod version:1.12.2-2.0.0.1

**Comment by necauqua** [comment] 2020-05-05 07:25
Wow, this is new.
Well I cant reproduce, obviously.

Possibly it thinks that you collide with the blocks you're standing on?
Can you test it while being in the air?

Anyway, not enough info, and I am not working on the mod currently.
Big rework expected to be done this summer, so as with most bugs this may get randomly fixed or simply won't exist in new code.

**Comment by SkyfrostgamingYT** [comment] 2020-05-05 17:20
I figure it out, it is a bug with the up, down, and all around mod.

**Comment by LorenzoPapi** [comment] 2020-07-27 07:53
Just tested this issue, basically the hitbox doesn't get changed when you resize and Minecraft thinks that you are being suffocated by a block (confirmed in fixed-mixin version), tested with forge 1.12.2-14.23.5.2854 (the latest)
Debug log=https://gist.github.com/LorenzoPapi/13cc465ce86481fd27bb2543feefca51

**Comment by necauqua** [comment] 2021-02-11 07:38
Ok while latest mixin version has no hitbox issues, the gravity simply does not work (the camera is rotated and thats it).

This is due to 1.12 Forge+Mixin limitations not allowing udaa coremod to work, nothing I can do about that.

So yeah wontfix I guess, should work (or at least no fail as completely until I fix it) if both mods get updated to 1.13+ at some point.

**Closed as completed by necauqua** 2021-02-11 07:38 UTC
Labels: bug, wontfix, mod compat
