### ISSUE TITLE
When I try to use this mod with mod Optifine 1.12.2, the game crashes. 

### ISSUE THREAD

**Issue by Devarious0** [necauqua/chiseled-me#23] opened 2019-12-20 23:59 UTC
When I try to use this mod with mod Optifine 1.12.2, the game does not start. 

**Additional information:**
- crashlog file or gist: 
- `fml-latest.log` file: *highly recommended to provide*
[2019-12-20-4.log](https://github.com/necauqua/chiseled-me/files/3990809/2019-12-20-4.log)

**Comment by necauqua** [comment] 2019-12-21 13:27
First, you use the 2.0.0.0 version which crashes by itself, you need to use 2.0.0.1

Second, interesting enough, in the log you sent it crashes because of Optifine itself somehow, does that work for you without my mod?

And third, yes, this mod was known to never work with Optifine since the beginning, and Optifine is already the first in the list of mods to be checked for mod compat issues.

Thanks for your input, but also closing this as duplicate of #16, since nothing changed about optifine support (the lack of it) since then

**Closed as completed by necauqua** 2019-12-21 13:27 UTC
Labels: duplicate, crash
