### ISSUE TITLE
Giant mode bug

### ISSUE THREAD

**Issue by buckted** [necauqua/chiseled-me#19] opened 2019-10-15 11:47 UTC
Everytime i try to walk if i'm 2 size bigger, i get teleported up 10 blocks, and if it's 32 times bigger, i just get teleported like -6000 blocks and i'm starting to die.

Can someone help me?

**Comment by LaytonBaccea** [comment] 2019-10-15 17:50
I dont know that bug 🤔  i have never encountered it. Perhaps Anton can fix it

**Comment by necauqua** [comment] 2019-10-15 21:38
duplicate of #2

**Closed as completed by necauqua** 2019-10-15 21:38 UTC
Labels: duplicate
