### ISSUE TITLE
Camera not working properly with Galacticraft

### ISSUE THREAD

**Issue by ultra421** [necauqua/chiseled-me#36] opened 2020-03-24 20:49 UTC
**Description**
Camera not going up/down according to size, fog changes according to size.

**To reproduce**
Using any size recalibrator

**Expected behavior**
Camera going up/down.

**Screenshots**
![1 to 1](https://user-images.githubusercontent.com/62622714/77475118-9669ad80-6e18-11ea-8736-5b3062242ed9.png)
![1 to 2](https://user-images.githubusercontent.com/62622714/77475166-aaadaa80-6e18-11ea-9de4-1fad278eb4d1.png)
![1 to 32](https://user-images.githubusercontent.com/62622714/77475241-cadd6980-6e18-11ea-9f93-5eb2d749a211.png)

**Additional information:**
- Installed mods: 
[crash-2020-03-24_20.18.24-client.txt](https://github.com/necauqua/chiseled-me/files/4377591/crash-2020-03-24_20.18.24-client.txt) A crash log not related to the mod, but has the mod list.

- Forge version: *14.23.5.2847*
- Mod version: *1.12.2-2.0.0.1.jar*

**Comment by necauqua** [comment] 2020-03-24 22:29
Well this is one of the main functions of the mod which obviously worked, so this must be caused by yet another mod compatibility issue, I will check your mods too at some point.

**Comment by minimutson** [comment] 2020-06-22 02:36
Same issue, but the only mod I have found to be common ground is
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)

(Edit)
Upon further testing, I have reached the conclusion that MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar) is the culprit of the camera issue. I hope this helped!

-minimutson 6/21/2020 10:40 PM EST

**Comment by necauqua** [comment] 2020-06-22 06:51
This helped :)

**Comment by necauqua** [comment] 2020-07-27 21:43
confirmed by @LorenzoPapi on discord

**Comment by necauqua** [comment] 2021-02-03 18:25
Fixed in ede2651

**Closed as completed by necauqua** 2021-02-03 18:25 UTC
Labels: bug, confirmed, mod compat
