### ISSUE TITLE
Commands/Gamerules

### ISSUE THREAD

**Issue by SonicJDF** [necauqua/chiseled-me#14] opened 2019-07-13 13:28 UTC
I think at the moment there is some good commands but there could always be more!

Gamerule to set size of all newly spawned mobs to a certain size.

Command to change the current players size
Example:
1 - 0.2. *First time using command*
0.8 - 0.2 *Second time using command*
0.6 - 0.2 *Third time and so on*

**Comment by LaytonBaccea** [comment] 2019-07-13 16:02
Hhhmmm....  🤔   I have thought of this myself

**Comment by SonicJDF** [comment] 2019-07-13 17:09
That's cool that we have the same ideas. I can't wait till the 1.11.2 version is bug fixed and hopefully with new content.

**Comment by necauqua** [comment] 2019-07-14 13:29
ok so there is an absolute /setsizeof command and you want relative, got it.
Gamerule is a neat idea, added to the list too :)

**Comment by necauqua** [comment] 2019-12-17 12:54
Welp, this is a two-part issue (don't do that, open two separate ones) and one part is done - the server command is now much more useful

**Comment by necauqua** [comment] 2021-01-22 00:20
"Second part" of the issue is done in the discord beta, there are gamerules now.
Will close this issue once the actual code is on GitHub finally.

**Comment by necauqua** [comment] 2021-02-03 18:24
Fixed in ede2651

**Closed as completed by necauqua** 2021-02-03 18:24 UTC
Labels: feature request
