### ISSUE TITLE
Chiseled me crash

### ISSUE THREAD

**Issue by UpsideDownFoxxo** [necauqua/chiseled-me#24] opened 2019-12-23 13:33 UTC
[latest.log](https://github.com/necauqua/chiseled-me/files/3995120/latest.log)

**Comment by necauqua** [comment] 2019-12-26 11:47
You have OptiFine installed, which is (for now) not compatible with Chiseled Me
And it is the first one in the list of mods to be checked for compatibility issues

Closing this as another duplicate of #16

**Closed as completed by necauqua** 2019-12-26 11:47 UTC
Labels: duplicate, crash
