### ISSUE TITLE
Player resizing broken with galacticraft [1.12.2]

### ISSUE THREAD

**Issue by Scraft161** [necauqua/chiseled-me#71] opened 2020-10-10 19:25 UTC
when using both galacticraft and chiseled me for 1.12.2 the player camera stays at the same height and the player hitbox sizing isn't working like it's supposed to.

this could be an issue with conflicting ASM code on either side.

**Comment by LorenzoPapi** [comment] 2020-10-10 19:28
The latest release of chiseled me is incompatible with Galactricraft, but in the discord server of the mod there is a beta with a fix for it (if you really want to use Chiseled me with Galactricraft now and can't wait for the new release to come out)

**Comment by Scraft161** [comment] 2020-10-10 20:42
thank you, I am working on a pack featuring Chiseled me as one of the mods but sadly enough GalactiCraft isn't the only mod causing issues, I know VanillaFix messes with the player model and prevents chiseled me from starting but I'll open an issue for that once I have more information.

thank you very much for pointing this out to me, is it ok if I keep this issue open untill the release is on curseforge.

**Comment by necauqua** [comment] 2020-10-10 20:56
The discord release is technically a beta (albeit "released" only in discord) so you are free to use it.
Or like, you can clone this repo and compile it yourself :)
Yeah I was a bit busy with all sorts of stuff, so I'll try to make a release finally at some point

**Comment by landpointpro** [comment] 2020-10-26 04:26
i am having the same issue where the game opens but then closes with no error on sky factory 4 modpack and added this mod to it wont allow it to start

**Comment by LorenzoPapi** [comment] 2020-10-26 05:00
@landpointpro if you don't know why the game doesn't start, I suggest you to make a new issue and post all the required files to make the developer possible to try to fix the issue. Reply here only if the issue is related to the Galactricraft mod

**Comment by necauqua** [comment] 2021-01-21 23:52
Closing as duplicate of #36, fixed in discord beta

**Closed as completed by necauqua** 2021-01-21 23:52 UTC
